=== BackupTheBerlios/fshare/v3/etat.dtd
<?xml version='1.0' encoding='iso-8859-1'?>
<!--
    Typical usage:
    <?xml version="1.0"?>
    <!DOCTYPE etat SYSTEM "etat.dtd">
    <etat>
    ...
    </etat>
-->

<!ELEMENT client (date)*>
<!ATTLIST client
    name CDATA #IMPLIED
    id NMTOKEN #REQUIRED
  >

<!ELEMENT date EMPTY>
<!ATTLIST date
    année NMTOKEN #REQUIRED
    mois NMTOKEN #REQUIRED
    jour NMTOKEN #REQUIRED
    heure NMTOKEN #REQUIRED
    minute NMTOKEN #REQUIRED
  >

<!ELEMENT etat (date,fichiers)>
<!ATTLIST etat
    xmlns CDATA #FIXED "http://deptinfo.unice.fr/minfo/ns/p2p"
  >

<!ELEMENT fichier (nom,date,taille,type,client+)>

<!ELEMENT fichiers (fichier)*>

<!ELEMENT nom (#PCDATA)>

<!ELEMENT taille (#PCDATA)>

<!ELEMENT type (#PCDATA)>

=== BackupTheBerlios/fshare/v3/etat.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE etat SYSTEM "etat.dtd">
<etat xmlns="http://deptinfo.unice.fr/minfo/ns/p2p">
<date jour="04" mois="04" année="2004" heure="10" minute="05"/>
<fichiers>
<fichier>
<nom>Client.class</nom>
<taille>4583</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>Profiles.usr</nom>
<taille>36</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>MD_autosave.ugd</nom>
<taille>63123</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>Repository</nom>
<taille>12</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>0.41638953089730546-Authorized_P2P_LindowsLive.txt</nom>
<taille>0</taille>
<type>DOCUMENT</type>
</fichier>
<fichier>
<nom>Entries</nom>
<taille>479</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>MD.cfg</nom>
<taille>585</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>java.policy</nom>
<taille>56</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>v3.jpx.local</nom>
<taille>2143</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>aide</nom>
<taille>1328</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>MD.opt</nom>
<taille>749</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>MD1.ugd</nom>
<taille>63123</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>MD0.ugd</nom>
<taille>63123</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>MD2.ugd</nom>
<taille>63123</taille>
<type>AUTRE</type>
</fichier>
<fichier>
<nom>Root</nom>
<taille>55</taille>
<type>AUTRE</type>
</fichier>
</fichiers>
</etat>
